### ISSUE TITLE
Support for arm7 devices

### ISSUE THREAD

**Issue by hosnifraj1** [bdloser404/Fluttermux#1]
If you make flutter support arm7 devices, you will get so much popularity and you will help hundred of thousands of mobile developer. I hope you understand. - Hosni

**Comment by mdHABIBURRAHMANHABIB1** [comment]
arm7 is not possible my brother.
- FlutterSDK support Linux-arm64 so we made it possible for aarch64 on Termux Natively.

**Comment by dhosni** [comment]
I will close the issue after I get an answer from the developer itself.

**Comment by bdloser404** [comment]
it should work only for flutter sdk.
i will try.

dont close this issue for now.

**Comment by dhosni** [comment]
Okay, it's gonna be fire if it works on arm7 devices.

**Comment by bdloser404** [comment]
> Okay, it's gonna be fire if it works on arm7 devices.

#### ARMhf(ARM7 or ARM*) cant handle flutter sdk

- It does support glibc but i cant make it work for FLutter sdk
- `ld-linux-armhf.so.3` cant be use as interpreter of dart

you can close this issue
