### ISSUE TITLE
Can not run dart binary getting error

### ISSUE THREAD

**Issue by ANIL80531** [bdloser404/Fluttermux#5]
`$ ./dart

./dart: error while loading shared libraries: libdl.so: cannot open shared object file: No such file or directory
$`

**Comment by ANIL80531** [comment]
`~/.../dart-sdk/bin $ ldd dart

libdl.so.2 => /data/data/com.termux/files/usr/glibc/lib/libdl.so.2
        libpthread.so.0 => /data/data/com.termux/files/usr/glibc/lib/libpthread.so.0
        libm.so.6 => /data/data/com.termux/files/usr/glibc/lib/libm.so.6
        libc.so.6 => /data/data/com.termux/files/usr/glibc/lib/libc.so.6
        ld-linux-aarch64.so.1 => /data/data/com.termux/files/usr/glibc/lib/ld-linux-aarch64.so.1
~/.../dart-sdk/bin $`

**Comment by bdloser404** [comment]
can you please share more information.

`$ uname -a`

and make sure you have glibc inside `cd $PREFIX/`

sent this output as screenshot

**Comment by bdloser404** [comment]
> `~/.../dart-sdk/bin $ ldd dart
> 
> libdl.so.2 => /data/data/com.termux/files/usr/glibc/lib/libdl.so.2 libpthread.so.0 => /data/data/com.termux/files/usr/glibc/lib/libpthread.so.0 libm.so.6 => /data/data/com.termux/files/usr/glibc/lib/libm.so.6 libc.so.6 => /data/data/com.termux/files/usr/glibc/lib/libc.so.6 ld-linux-aarch64.so.1 => /data/data/com.termux/files/usr/glibc/lib/ld-linux-aarch64.so.1 ~/.../dart-sdk/bin $`

and make sure you've `unset LD_PRELOAD` on ~/.bashrc or ~/.zshrc depending on which shell you are using

**Comment by ANIL80531** [comment]
![Screenshot_20231010-125720_Termux](https://github.com/bdloser404/Fluttermux/assets/61663725/4d6e663d-76a0-444d-853e-28f6172dab52)

**Comment by ANIL80531** [comment]
I think this worked 
unset LD_PRELOAD
Now dart is running

**Comment by bdloser404** [comment]
> I think this worked unset LD_PRELOAD Now dart is running

This is bcz by default termux locking lib for `$PREFIX/lib`. thats why we need to unset it first

**Comment by ANIL80531** [comment]
![Screenshot_20231010-130326_Termux](https://github.com/bdloser404/Fluttermux/assets/61663725/01cca92c-3d14-4778-a5c6-4d269bf765b2)
I'm getting this error
I'm running your install.sh step by step as your curl link do not work

**Comment by ANIL80531** [comment]
No it's again showing no such file

**Comment by ANIL80531** [comment]
![Uploading Screenshot_20231010-130834_Termux.png…]()

**Comment by ANIL80531** [comment]
![Screenshot_20231010-130834_Termux](https://github.com/bdloser404/Fluttermux/assets/61663725/c4c1d8be-8529-453c-a7ae-8e724dbc78da)

**Comment by bdloser404** [comment]
> ![Screenshot_20231010-130834_Termux](https://user-images.githubusercontent.com/61663725/273815511-c4c1d8be-8529-453c-a7ae-8e724dbc78da.png)

if dart command  is working then i think everything is fine.
check dart libs with `ldd dart`

**Comment by ANIL80531** [comment]
![Screenshot_20231010-131134_Termux](https://github.com/bdloser404/Fluttermux/assets/61663725/d0e0b615-8e67-4846-8686-ef54db4f14cf)
Also do not work in dart-sdk/bin/utils folder

**Comment by ANIL80531** [comment]
![Screenshot_20231010-131424_Termux](https://github.com/bdloser404/Fluttermux/assets/61663725/7cc63a6c-403e-48b1-aa2d-8af7144fd083)
I have glibc install and ld-linux-aarch64.so.1 file is also present.

**Comment by bdloser404** [comment]
gen_snapshot.sym is not elf. so you are getting error when you are trying to patch it with *

**Comment by ANIL80531** [comment]
Yeah * was problem 😅 thanks

**Comment by ANIL80531** [comment]
![Screenshot_20231010-132520_Termux](https://github.com/bdloser404/Fluttermux/assets/61663725/8a5d78ca-d25c-4bfd-aeaa-2f4b7bf11c67)

**Comment by ANIL80531** [comment]
![Screenshot_20231010-132708_Termux](https://github.com/bdloser404/Fluttermux/assets/61663725/e798f1db-1e5e-438b-a0b5-d3c099748fe1)
libdl.so is in different dir not in glibc folder
